// Generated by CoffeeScript 2.5.1
(function() {

  /* начальная координата - левый средний угол звезды */
  /* Этот метод выполняется при клике  */
  var drawRect, drawStar, findPos, handler, rgbToHex, starsCanvas, starsCanvasElement, statusCanvas, statusCanvasElement;

  starsCanvasElement = document.getElementById('stars-canvas');

  starsCanvas = starsCanvasElement.getContext('2d');

  statusCanvasElement = document.getElementById('status');

  statusCanvas = statusCanvasElement.getContext('2d');

  drawRect = function(ctx, color = '#fff', params = [0, 0, 600, 50]) {
    ctx.beginPath();
    ctx.rect(params[0], params[1], params[2], params[3]);
    ctx.fillStyle = color;
    return ctx.fill();
  };

  drawStar = function(x0 = 0, y0 = 0, fill = 'black') {
    starsCanvas.beginPath();
    starsCanvas.moveTo(x0, 70 + y0);
    starsCanvas.lineTo(72 + x0, 70 + y0);
    starsCanvas.lineTo(95 + x0, y0);
    starsCanvas.lineTo(117 + x0, 70 + y0);
    starsCanvas.lineTo(190 + x0, 70 + y0);
    starsCanvas.lineTo(131 + x0, 112 + y0);
    starsCanvas.lineTo(154 + x0, 180 + y0);
    starsCanvas.lineTo(95 + x0, 138 + y0);
    starsCanvas.lineTo(36 + x0, 180 + y0);
    starsCanvas.lineTo(59 + x0, 112 + y0);
    starsCanvas.closePath();
    starsCanvas.strokeStyle = fill;
    starsCanvas.stroke();
    starsCanvas.fillStyle = fill;
    return starsCanvas.fill();
  };

  /* Сначала рисуем белый квадрат */
  drawRect(starsCanvas, '#fff', [0, 0, 600, 600]);

  /* Рисуем звезды */
  drawStar(20, 20, 'red');

  drawStar(380, 20, 'blue');

  drawStar(200, 200, 'green');

  drawStar(20, 380, 'yellow');

  drawStar(380, 380);

  /* Риуем полоску статуса */
  drawRect(statusCanvas);

  rgbToHex = function(r, g, b) {
    if (r > 255 || g > 255 || b > 255) {
      throw "Invalid color component";
    }
    return ((r << 16) | (g << 8) | b).toString(16);
  };

  findPos = function(obj) {
    var curleft, curtop;
    curleft = 0;
    curtop = 0;
    if (obj.offsetParent) {
      while (true) {
        curleft += obj.offsetLeft;
        curtop += obj.offsetTop;
        if (obj = obj.offsetParent) {
          break;
        }
      }
      return {
        x: curleft,
        y: curtop
      };
    }
    return void 0;
  };

  handler = function(e) {
    var c, hex, p, pos, x, y;
    pos = findPos(this);
    x = e.pageX - pos.x;
    y = e.pageY - pos.y;
    c = this.getContext('2d');
    p = c.getImageData(x, y, 1, 1).data;
    hex = "#" + ("000000" + rgbToHex(p[0], p[1], p[2])).slice(-6);
    return drawRect(statusCanvas, hex);
  };

  starsCanvasElement.addEventListener('click', handler);

}).call(this);
