// Generated by CoffeeScript 2.5.1
(function() {

  /* начальная координата - левый средний угол звезды */
  var drawStar, starsCanvas, starsCanvasElement;

  starsCanvasElement = document.getElementById('stars-canvas');

  starsCanvas = starsCanvasElement.getContext('2d');

  drawStar = function(x0 = 0, y0 = 0) {
    starsCanvas.beginPath();
    starsCanvas.moveTo(x0, 70 + y0);
    starsCanvas.lineTo(72 + x0, 70 + y0);
    starsCanvas.lineTo(95 + x0, y0);
    starsCanvas.lineTo(117 + x0, 70 + y0);
    starsCanvas.lineTo(190 + x0, 70 + y0);
    starsCanvas.lineTo(131 + x0, 112 + y0);
    starsCanvas.lineTo(154 + x0, 180 + y0);
    starsCanvas.lineTo(95 + x0, 138 + y0);
    starsCanvas.lineTo(36 + x0, 180 + y0);
    starsCanvas.lineTo(59 + x0, 112 + y0);
    starsCanvas.closePath();
    starsCanvas.strokeStyle = '#b4241b';
    return starsCanvas.stroke();
  };

  drawStar(20, 20);

  drawStar(380, 20);

  drawStar(200, 200);

  drawStar(200, 200);

  drawStar(20, 380);

  drawStar(380, 380);

}).call(this);
